#!/usr/bin/env bash
# webserver.sh - nginx and nginx-rtmp configuration.
#
# Every port in these templates comes from a variable. Upstream hardcoded the
# stock ports (25461 client, 25462 rtmp, 25463 https) in some files while making
# the client port configurable in others, so choosing a non-default client port
# silently broke RTMP authentication and HTTPS stream URLs.

generate_self_signed_cert() {
    local conf_dir="${PANEL_PATH}/nginx/conf"
    local crt="${conf_dir}/server.crt"
    local key="${conf_dir}/server.key"

    if [[ -f "$crt" && -f "$key" ]]; then
        log_info "TLS certificate already present."
        return 0
    fi

    log_info "Generating a self-signed TLS certificate"

    openssl req -x509 -nodes -newkey rsa:2048 -days 3650 \
        -keyout "$key" -out "$crt" \
        -subj "/CN=${PANEL_DOMAIN:-$PUBLIC_IP}" >/dev/null 2>&1 \
        || { log_warn "Certificate generation failed; HTTPS will be disabled."; return 1; }

    chown xtreamcodes:xtreamcodes "$crt" "$key"
    chmod 0400 "$key"
    chmod 0444 "$crt"

    log_ok "Self-signed certificate generated (replace it with a real one for production)."
}

write_nginx_conf() {
    log_step "Writing the nginx configuration"

    local conf_dir="${PANEL_PATH}/nginx/conf"
    local conf="${conf_dir}/nginx.conf"

    mkdir -p "$conf_dir"
    [[ -f "$conf" ]] && backup_file "$conf" >/dev/null

    local ssl_block=""
    if [[ "$ENABLE_HTTPS" == "yes" ]] && generate_self_signed_cert; then
        # TLSv1.2 and TLSv1.3 only.
        #
        # Upstream shipped: ssl_protocols SSLv3 TLSv1.1 TLSv1.2;
        # SSLv3 has been broken since POODLE (2014) and TLS 1.1 was deprecated
        # by RFC 8996. Neither belongs in a config written today.
        ssl_block=$(cat <<EOF

        listen ${CLIENT_HTTPS_PORT} ssl;
        ssl_certificate     server.crt;
        ssl_certificate_key server.key;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
        ssl_prefer_server_ciphers off;
        ssl_session_cache   shared:SSL:10m;
        ssl_session_timeout 10m;
EOF
)
    fi

    # The admin server block. When --admin-allow-ip is given, access is
    # restricted at the web server as well as at the firewall.
    local admin_acl=""
    if [[ -n "${ADMIN_ALLOW_IP:-}" ]]; then
        admin_acl=$(printf '        allow %s;\n        allow 127.0.0.1;\n        deny all;\n' "$ADMIN_ALLOW_IP")
    fi

    cat >"$conf" <<EOF
# Generated by xtreamui-installer on $(date '+%Y-%m-%d %H:%M:%S')
# Regenerate with: tools/regenerate-nginx.sh

user  xtreamcodes;
worker_processes  auto;
worker_rlimit_nofile 300000;

events {
    worker_connections 16000;
    use epoll;
    accept_mutex on;
    multi_accept on;
}

thread_pool pool_xtream threads=32 max_queue=0;

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile           on;
    tcp_nopush         on;
    tcp_nodelay        on;
    reset_timedout_connection on;
    gzip off;

    fastcgi_read_timeout 200;
    access_log off;
    keepalive_timeout 10;
    send_timeout 20m;
    sendfile_max_chunk 512k;
    lingering_close off;
    aio threads=pool_xtream;

    client_body_timeout 13s;
    client_header_timeout 13s;
    client_max_body_size 3m;

    limit_req_zone \$binary_remote_addr zone=one:30m rate=${RATE_LIMIT}r/s;

    include balance.conf;

    # ---- Client access ----------------------------------------------------
    server {
        listen ${CLIENT_PORT};${ssl_block}

        index index.php index.html index.htm;
        root ${PANEL_PATH}/wwwdir/;

        server_tokens off;
        chunked_transfer_encoding off;

        if ( \$request_method !~ ^(GET|POST)\$ ) {
            return 405;
        }

        rewrite ^/live/(.*)/(.*)/(.*)\.(.*)\$   /streaming/clients_live.php?username=\$1&password=\$2&stream=\$3&extension=\$4 break;
        rewrite ^/movie/(.*)/(.*)/(.*)\$        /streaming/clients_movie.php?username=\$1&password=\$2&stream=\$3&type=movie break;
        rewrite ^/series/(.*)/(.*)/(.*)\$       /streaming/clients_movie.php?username=\$1&password=\$2&stream=\$3&type=series break;
        rewrite ^/(.*)/(.*)/(.*)\.ch\$          /streaming/clients_live.php?username=\$1&password=\$2&stream=\$3&extension=ts break;
        rewrite ^/(.*)\.ch\$                    /streaming/clients_live.php?extension=ts&stream=\$1&qs=\$query_string break;
        rewrite ^/ch(.*)\.m3u8\$                /streaming/clients_live.php?extension=m3u8&stream=\$1&qs=\$query_string break;
        rewrite ^/hls/(.*)/(.*)/(.*)/(.*)/(.*)\$        /streaming/clients_live.php?extension=m3u8&username=\$1&password=\$2&stream=\$3&type=hls&segment=\$5&token=\$4 break;
        rewrite ^/hlsr/(.*)/(.*)/(.*)/(.*)/(.*)/(.*)\$  /streaming/clients_live.php?token=\$1&username=\$2&password=\$3&segment=\$6&stream=\$4&key_seg=\$5 break;
        rewrite ^/timeshift/(.*)/(.*)/(.*)/(.*)/(.*)\.(.*)\$  /streaming/timeshift.php?username=\$1&password=\$2&stream=\$5&extension=\$6&duration=\$3&start=\$4 break;
        rewrite ^/timeshifts/(.*)/(.*)/(.*)/(.*)/(.*)\.(.*)\$ /streaming/timeshift.php?username=\$1&password=\$2&stream=\$4&extension=\$6&duration=\$3&start=\$5 break;
        rewrite ^/(.*)/(.*)/(\d+)\$             /streaming/clients_live.php?username=\$1&password=\$2&stream=\$3&extension=ts break;
        rewrite ^/server/load.php\$             /portal.php break;

        location /stalker_portal/c {
            alias ${PANEL_PATH}/wwwdir/c;
        }

        location = /progress.php {
            allow 127.0.0.1;
            deny all;
            fastcgi_pass php;
            include fastcgi_params;
            fastcgi_ignore_client_abort on;
            fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
            fastcgi_param SCRIPT_NAME \$fastcgi_script_name;
        }

        location ~ \.php\$ {
            limit_req zone=one burst=${RATE_BURST};
            try_files \$uri =404;
            fastcgi_index index.php;
            fastcgi_pass php;
            include fastcgi_params;
            fastcgi_buffering on;
            fastcgi_buffers 96 32k;
            fastcgi_buffer_size 32k;
            fastcgi_max_temp_file_size 0;
            fastcgi_keep_conn on;
            fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
            fastcgi_param SCRIPT_NAME \$fastcgi_script_name;
        }
    }

    # ---- Admin panel ------------------------------------------------------
    server {
        listen ${ADMIN_PORT};

        index index.php index.html index.htm;
        root ${PANEL_PATH}/admin/;

        server_tokens off;
${admin_acl}
        location ~ \.php\$ {
            limit_req zone=one burst=${RATE_BURST};
            try_files \$uri =404;
            fastcgi_index index.php;
            fastcgi_pass php;
            include fastcgi_params;
            fastcgi_buffering on;
            fastcgi_buffers 96 32k;
            fastcgi_buffer_size 32k;
            fastcgi_max_temp_file_size 0;
            fastcgi_keep_conn on;
            fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
            fastcgi_param SCRIPT_NAME \$fastcgi_script_name;
        }
    }

    # ---- ISP module (loopback only) ---------------------------------------
    server {
        listen 127.0.0.1:${ISP_PORT};
        root ${PANEL_PATH}/isp/;

        location / {
            allow 127.0.0.1;
            deny all;
        }

        location ~ \.php\$ {
            limit_req zone=one burst=${RATE_BURST};
            try_files \$uri =404;
            fastcgi_index index.php;
            fastcgi_pass php;
            include fastcgi_params;
            fastcgi_buffering on;
            fastcgi_buffers 96 32k;
            fastcgi_buffer_size 32k;
            fastcgi_max_temp_file_size 0;
            fastcgi_keep_conn on;
            fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
            fastcgi_param SCRIPT_NAME \$fastcgi_script_name;
        }
    }
}
EOF

    log_ok "nginx.conf written (admin ${ADMIN_PORT}, client ${CLIENT_PORT}, isp ${ISP_PORT} loopback-only)."
}

write_nginx_rtmp_conf() {
    log_step "Writing the nginx-rtmp configuration"

    local conf_dir="${PANEL_PATH}/nginx_rtmp/conf"
    local conf="${conf_dir}/nginx.conf"

    mkdir -p "$conf_dir"
    [[ -f "$conf" ]] && backup_file "$conf" >/dev/null

    # The callback port is the fix for the bug that breaks RTMP whenever the
    # client port is not the stock 25461: these on_play/on_publish hooks call
    # back into the client vhost, and upstream hardcoded 25461 here regardless
    # of what the operator chose. If nothing listens there, every RTMP auth
    # attempt fails silently.
    cat >"$conf" <<EOF
# Generated by xtreamui-installer on $(date '+%Y-%m-%d %H:%M:%S')

user  xtreamcodes;
worker_processes  1;
worker_rlimit_nofile 300000;

events {
    worker_connections 16000;
    use epoll;
}

rtmp_auto_push on;

rtmp {
    server {
        listen ${RTMP_PORT};

        interleave on;
        wait_video on;
        idle_streams off;
        chunk_size 4096;
        notify_method get;

        application live {
            live on;
            record off;

            on_play      http://127.0.0.1:${CLIENT_PORT}/streaming/rtmp.php;
            on_publish   http://127.0.0.1:${CLIENT_PORT}/streaming/rtmp.php;
            on_play_done http://127.0.0.1:${CLIENT_PORT}/streaming/rtmp.php;
        }
    }
}

http {
    server {
        listen 127.0.0.1:${RTMP_STAT_PORT};
        server_name localhost;

        allow 127.0.0.1;
        deny all;

        location /control { rtmp_control all; }
        location /stat    { rtmp_stat all; }
    }
}
EOF

    log_ok "nginx_rtmp.conf written (rtmp ${RTMP_PORT}, callbacks -> 127.0.0.1:${CLIENT_PORT})."
}

configure_php() {
    log_step "Configuring PHP"

    local php_ini="${PANEL_PATH}/php/lib/php.ini"

    if [[ ! -f "$php_ini" ]]; then
        log_warn "php.ini not found at $php_ini; skipping."
        return 0
    fi

    backup_file "$php_ini" >/dev/null

    _set_php_ini "$php_ini" "date.timezone"     "$TIMEZONE"
    _set_php_ini "$php_ini" "expose_php"        "Off"
    _set_php_ini "$php_ini" "display_errors"    "Off"
    _set_php_ini "$php_ini" "log_errors"        "On"
    _set_php_ini "$php_ini" "allow_url_include" "Off"

    log_ok "PHP configured (timezone ${TIMEZONE}, errors hidden from output)."
}

_set_php_ini() {
    local file="$1" key="$2" value="$3"
    if grep -qE "^;?\s*${key}\s*=" "$file"; then
        sed -i -E "s|^;?\s*${key}\s*=.*|${key} = ${value}|" "$file"
    else
        printf '%s = %s\n' "$key" "$value" >>"$file"
    fi
}

test_nginx_config() {
    log_step "Validating the nginx configuration"

    # This is the check that would have caught the invalid-port failure before
    # anything was started, instead of after.
    local nginx_bin="${PANEL_PATH}/nginx/sbin/nginx"
    local conf="${PANEL_PATH}/nginx/conf/nginx.conf"

    if [[ ! -x "$nginx_bin" ]]; then
        log_warn "nginx binary not found at $nginx_bin; skipping validation."
        return 0
    fi

    local output
    if output=$("$nginx_bin" -t -c "$conf" 2>&1); then
        log_ok "nginx configuration is valid."
    else
        log_error "$output"
        die "The generated nginx configuration is invalid. Nothing was started."
    fi
}
